<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>UnityEngine.UIModule</AssemblyName>
    <RootNamespace>UnityEngine</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UnityEngine.CoreModule\UnityEngine.CoreModule.csproj" />
  </ItemGroup>
</Project>
